# Generated by Django 3.0.9 on 2020-08-25 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('python', '파이썬'), ('c', 'C'), ('comp_arc', '컴퓨터구조'), ('os', '운영체제'), ('ds', '데이타구조'), ('LD', '논리설계'), ('algo', '알고리즘'), ('java', '자바'), ('database', '데이타베이스'), ('compiler', '컴파일러'), ('oodp', '객체지향'), ('elec_circuit', '전자회로'), ('circuit_theory', '회로이론'), ('etc', '기타')], default='etc', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('finding_match', models.BooleanField(default=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('cancel_reason', models.TextField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('fin_time', models.DateTimeField(null=True)),
                ('hit', models.PositiveIntegerField(default=0)),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_relation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('session_type', models.CharField(choices=[('online', '온라인'), ('offline', '오프라인'), ('onoff', '온/오프라인')], default='onoff', max_length=10)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('fin_time', models.DateTimeField(null=True)),
                ('hit', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=500, null=True)),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_waiting', models.BooleanField(default=True)),
                ('wait_time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('fin_time', models.DateTimeField(null=True)),
                ('tutee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_tutee', to=settings.AUTH_USER_MODEL)),
                ('tutor_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_session', to='matching.TutorSession')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False, null=True)),
                ('content', models.TextField()),
                ('join_tutee', models.TextField(null=True)),
                ('duration_time', models.PositiveIntegerField(choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60)], default=10)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='matching.Post')),
                ('tutee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutee', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('is_tutor', models.BooleanField(blank=True, default=False, null=True)),
                ('signin', models.BooleanField(default=False)),
                ('tutor_tutoringTime', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('content', models.TextField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.post')),
                ('tutorsession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.tutorsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
