# Generated by Django 3.0.8 on 2020-07-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_time',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='meeting_time',
            new_name='meeting_date',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='report_time',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='contact',
            new_name='phone',
        ),
    ]
