# Generated by Django 3.0.8 on 2020-07-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20200707_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='content',
            field=models.TextField(default='hiiiii'),
            preserve_default=False,
        ),
    ]
