# Generated by Django 3.0.8 on 2020-07-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_auto_20200707_1617'),
        ('matching', '0003_report_content'),
    ]

    operations = [
    ]
