# Generated by Django 3.0.8 on 2020-07-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_merge_20200707_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cancel_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='finding_match',
            field=models.NullBooleanField(default=False),
        ),
    ]
